name: Finish CI Build

on:
  workflow_run:
    workflows: ["Run CI Tests"]
    types:
      - completed

jobs:
  success:
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:

      - name: Update status Comment
        uses: actions-cool/maintain-one-comment@v3.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🚀 Stack Insights and Cloud Pod state for this CI build are available here: https://app.localstack.cloud/ci 🚀
            <!-- Sticky Pull Request Comment -->
          body-include: '<!-- Sticky Pull Request Comment -->'
          number: ${{ steps.pr.outputs.id }}

  # failed:
  #   runs-on: ubuntu-latest
  #   if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'failure'
  #   steps:
  #
  #     - name: Save the PR ID
  #       id: pr
  #       run: echo "::set-output name=id::$(<pr-id.txt)"
  #
  #     - name: Job failure
  #       uses: actions-cool/maintain-one-comment@v3.1.1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         body: |
  #           Deploy PR Preview failed.
  #           <!-- Sticky Pull Request Comment -->
  #         body-include: '<!-- Sticky Pull Request Comment -->'
  #         number: ${{ steps.pr.outputs.id }}
