name: Run CI Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Prepare LocalStack Build
        uses: LocalStack/setup-localstack/prepare@pr-integration
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Finish LocalStack Build
        uses: LocalStack/setup-localstack/finish@pr-integration
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Start LocalStack
        # uses: LocalStack/setup-localstack@v0.1.2
        uses: LocalStack/setup-localstack@pr-integration
        with:
          install-awslocal: 'true'
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          CI_PROJECT: whummer-ci-test
          CONFIGURATION: "DOCKER_FLAGS='-e CI_PROJECT=whummer-ci-test'"

      - name: Save PR number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > ./pr-id.txt

      - name: Upload PR number
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: pr
          path: ./pr-id.txt

      - name: Run tests
        run: |
          awslocal s3 mb s3://test123
          awslocal s3 ls | grep test123

          awslocal sqs create-queue --queue-name q1
          awslocal sqs create-queue --queue-name q2

          awslocal sns create-topic --name t1
          awslocal sns create-topic --name t2
