name: Start CI Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.1.2
        with:
          install-awslocal: 'true'
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          CI_PROJECT: whummer-ci-test
          CONFIGURATION: "DOCKER_FLAGS='-e CI_PROJECT=whummer-ci-test'"

      - name:
        run: |
          awslocal s3 mb s3://test123
          awslocal s3 ls | grep test123
